services:
  ntp:
    image: ntp:latest
    ports:
      - 3333:3333
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - 5432:5432
  java-coordinator:
    image: presto:java-coordinator
    environment:
      - DB_HOST=db
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_SCHEMA=public
    ports:
      - 8080:8080

